### ISSUE TITLE
Team total from all members vs team's direct total

### ISSUE THREAD

**Issue by techguydave** [daniellockard/nodecg-tiltify#7]
I'm working on using this to pull data from a team's campaign. I noticed that in the Tiltify API (and `tiltify-api-client`), there are two separate total fields: `amountRaised` for what was given directly to the team, and `totalAmountRaised` for all donations, including those given to members' supporting campaigns.

Right now this package only surfaces the former. It should also include a new field for the team total. I can open a PR for this.

**Comment by techguydave** [comment]
Looking at this some more, work needs to also be done to include the supporting campaigns in the recent/all donations as well. I'm not sure if this should be new replicants for "entire team's total/donations/etc", or if the package should just assume you want the full total if it has supporting campaigns and updating the current replicants.

**Comment by daniellockard** [comment]
Hey @synth3tk -- Sorry for just now seeing this. I'm totally down if you want to PR any of that. It's not a use case I have but if you can provide me with a campaign ID of a campaign with multiple supporting campaigns I can take a look :)  (A PR is always preferred though)

**Comment by techguydave** [comment]
No worries, we all get busy! I believe I have a working PR ready in my repo. I'll make a note to submit it once I revisit (which needs to be soon, admittedly).

**Comment by daniellockard** [comment]
Closing as super old
